server:
  port: 8081


spring:
  # security:
  #   user:
  #     name: "dinesh"
  #     password: "1234"
      
  application:
    name: tech-trekker

  datasource:
    url: "jdbc:mysql://localhost:3310/blog"
    username: "root"
    password: "or02r5780"

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
  




upload:
  file:
    profile: "profile_images"
    blog:
      banner: "blog_banner_images"
